FROM python:3.11-slim

WORKDIR /app

RUN pip install --no-cache-dir uv

COPY pyproject.toml ./
COPY uv.lock ./

RUN uv sync --frozen --no-dev

COPY . .

EXPOSE 8501

CMD ["/app/.venv/bin/streamlit", "run", "ui/app.py", "--server.address=0.0.0.0", "--server.port=8501"]
